name: Deploy to Github Pages
on:
  push:
    branches:
      - main

jobs:
  deployment:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Run deploy
        run: npm run deploy
