name: Deploy to Github Pages
on:
  push:
    branches:
      - main

jobs:
  deployment:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Create env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_VITE_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          file_name: .env
      - name: Run deploy
        run: |
          git config --global user.name $user_name
          git config --global user.email $user_email
          git remote set-url origin https://${github_token}@github.com/${repository}
          npm run deploy
        env:
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          github_token: ${{ secrets.DEPLOY_TOKEN }}
          repository: ${{ github.repository }}
